Repository thecourseforum/theCourseForum2, pull requests merged in 2020-10, with the labels that each got.

#160 Django API with DRF
  precommit
  requirements.txt
  tcf_core/settings.py
  tcf_website/api/__init__.py
  tcf_website/api/paginations.py
  tcf_website/api/serializers.py
  tcf_website/api/urls.py
  tcf_website/api/views.py
  tcf_website/urls.py
Labels: Enhancement

#166 tCF site landing page & style guide
  tcf_style_guide.pdf
  tcf_website/static/base/base.css
  tcf_website/static/base/bootstrap.min.css
  tcf_website/static/base/sidebar.css
  tcf_website/static/base/tcf-style.css
  tcf_website/static/browse/browse.css
  tcf_website/static/common/rating_card.css
  tcf_website/static/landing/landing-page.css
  tcf_website/templates/base/base.html
  tcf_website/templates/base/index.html
  tcf_website/templates/base/navbar.html
  tcf_website/templates/base/searchbar.html
  tcf_website/templates/base/sidebar.html
  tcf_website/templates/landing/landing.html
  tcf_website/templates/landing/landing_old.html
  tcf_website/views/index.py
  tcf_website/views/team_info.json
Labels: Product, UX/Design

#185 Slim down Dockerfile
  Dockerfile
Labels: Enhancement, Infra
