Repository thecourseforum/theCourseForum2, pull requests merged in 2020-11, with the labels that each got.

#186 Review Sorting Bug Fix
  tcf_website/static/common/sorting.js
  tcf_website/static/reviews/sort_reviews.js
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/reviews/reviews.html
Labels: P0, bug

#176 Edit profile form
  legacy_db/mysql2sqlite
  manage.py
  tcf_core/settings.py
  tcf_website/management/commands/other_schools_department_fix.py
  tcf_website/static/about/alum-pfps/bknaysi.jpg
  tcf_website/static/about/alum-pfps/skonuri.jpg
  tcf_website/static/base/img/alderman-and-peabody.jpg
  tcf_website/templates/base/messages.html
  tcf_website/templates/profile/profile.html
  tcf_website/views/profile.py
Labels: Enhancement, P0, Product

#164 Found a bug form
  .env.travis
  tcf_core/settings.py
  tcf_website/static/base/base.css
  tcf_website/static/base/bugform.js
  tcf_website/static/base/sidebar.css
  tcf_website/static/common/form.js
  tcf_website/static/department/loadMoreCourses.js
  tcf_website/templates/base/bugform.html
  tcf_website/templates/base/sidebar.html
  tcf_website/urls.py
  tcf_website/views/__init__.py
  tcf_website/views/discord.py
Labels: P0

#194 Search style
  tcf_website/templates/search/search.html
Labels: Enhancement, Jules, Product, UX/Design

#217 Revert PR#211 vote fix
  .eslintignore
  tcf_website/static/reviews/review.js
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/reviews/review.html
  tcf_website/templates/reviews/reviews.html
  tcf_website/templates/reviews/user_reviews.html
Labels: Needs Review

#197 Compact sidebar styling
  tcf_website/static/base/base.css
  tcf_website/static/base/navbar.css
  tcf_website/static/base/sidebar.css
  tcf_website/templates/base/bugform.html
  tcf_website/templates/base/navbar.html
  tcf_website/templates/base/sidebar.html
Labels: Needs Review

#223 Welcome modal
  tcf_website/templates/landing/landing.html
  tcf_website/views/index.py
Labels: Needs Review

#190 Instructor pages
  precommit
  tcf_website/models/models.py
  tcf_website/static/base/base.css
  tcf_website/static/base/tcf-style.css
  tcf_website/static/common/rating_card.css
  tcf_website/static/common/toolbar.css
  tcf_website/static/department/loadMoreCourses.js
  tcf_website/static/instructor/instructor.css
  tcf_website/templates/common/rating_card.html
  tcf_website/templates/common/toolbar.html
  tcf_website/templates/course/course.html
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/instructor/instructor.html
  tcf_website/templates/reviews/review.html
  tcf_website/views/browse.py
  tcf_website/views/search.py
Labels: Needs Review

#198 Update About Page
  tcf_website/static/about/about.css
  tcf_website/static/about/alum-pfps/hpathipati.jpg
  tcf_website/static/about/history/history.css
  tcf_website/static/about/javascript/about.js
  tcf_website/static/about/javascript/switch-subcontent.js
  tcf_website/static/about/team-pfps/ENG_Alex_Shen.jpg
  tcf_website/static/about/team-pfps/ENG_Jennifer_Long.jpg
  tcf_website/static/about/team-pfps/ENG_Jules_LeMenestrel.jpg
  tcf_website/static/about/team-pfps/MAD_Jeremy_Tran.jpg
  tcf_website/static/about/team-pfps/MAD_Kimberly_Vo.jpg
  tcf_website/static/about/team-pfps/MAD_Tina_Wang.jpg
  tcf_website/templates/about/about.html
  tcf_website/templates/about/contributors.html
  tcf_website/templates/about/current_team.html
  tcf_website/templates/about/history.html
  tcf_website/templates/about/privacy.html
  tcf_website/templates/about/sponsors.html
  tcf_website/urls.py
  tcf_website/views/__init__.py
  tcf_website/views/index.py
  tcf_website/views/team_alums.json
  tcf_website/views/team_info.json
Labels: Needs Review, Product

#195 Landing page fixes & updates
  tcf_website/static/about/team-pfps/ENG_Alex_Shen.webp
  tcf_website/static/about/team-pfps/ENG_Jack_Liu.webp
  tcf_website/static/about/team-pfps/ENG_Jennifer_Long.webp
  tcf_website/static/about/team-pfps/ENG_Jules_LeMenestrel.webp
  tcf_website/static/about/team-pfps/ENG_Vi_Nguyen.webp
  tcf_website/static/about/team-pfps/MAD_Davis_Delozier.webp
  tcf_website/static/about/team-pfps/MAD_Shirley_Chu.webp
  tcf_website/static/base/tcf-style.css
  tcf_website/static/landing/UVA_rotunda_logo.png
  tcf_website/static/landing/UVA_rotunda_logo_blue.png
  tcf_website/static/landing/dashboard.css
  tcf_website/static/landing/feedbackform.js
  tcf_website/static/landing/landing-page.css
  tcf_website/static/landing/landing.css
  tcf_website/templates/base/bugform.html
  tcf_website/templates/landing/dashboard.html
  tcf_website/templates/landing/landing.html
  tcf_website/views/team_info.json
Labels: Needs Review

#213 Fixed review UI mobile layout
  tcf_website/static/base/base.css
  tcf_website/static/reviews/review.css
  tcf_website/templates/reviews/review.html
  tcf_website/templates/reviews/reviews.html
Labels: Needs Review

#231 Review form modal
  tcf_website/templates/base/sidebar.html
  tcf_website/templates/landing/landing.html
  tcf_website/urls.py
Labels: Needs Review

#229 More landing page stuff (FAQ)
  tcf_website/static/base/tcf-style.css
  tcf_website/static/landing/feedbackform.js
  tcf_website/static/landing/landing.css
  tcf_website/templates/base/searchbar.html
  tcf_website/templates/landing/landing.html
  tcf_website/views/_faqs.json
  tcf_website/views/index.py
Labels: Needs Review

#209 Grades data and UI
  Dockerfile
  README.md
  load_data
  package-lock.json
  package.json
  tcf_website/admin.py
  tcf_website/api/serializers.py
  tcf_website/api/views.py
  tcf_website/management/commands/grade_data/csv/2011_fall.csv
  tcf_website/management/commands/grade_data/csv/2012_fall.csv
  tcf_website/management/commands/grade_data/csv/2012_spring.csv
  tcf_website/management/commands/grade_data/csv/2013_fall.csv
  tcf_website/management/commands/grade_data/csv/2013_spring.csv
  tcf_website/management/commands/grade_data/csv/2014_fall.csv
  tcf_website/management/commands/grade_data/csv/2014_spring.csv
  tcf_website/management/commands/grade_data/csv/2015_fall.csv
  tcf_website/management/commands/grade_data/csv/2015_spring.csv
  tcf_website/management/commands/grade_data/csv/2016_fall.csv
  tcf_website/management/commands/grade_data/csv/2016_spring.csv
  tcf_website/management/commands/grade_data/csv/2017_fall.csv
  tcf_website/management/commands/grade_data/csv/2017_spring.csv
  tcf_website/management/commands/grade_data/csv/2018_fall.csv
  tcf_website/management/commands/grade_data/csv/2018_spring.csv
  tcf_website/management/commands/grade_data/csv/2019_spring.csv
  tcf_website/management/commands/load_grades.py
  tcf_website/models/__init__.py
  tcf_website/models/models.py
  tcf_website/static/course/course_professor.css
  tcf_website/static/course/javascript/course_data.js
  tcf_website/static/department/loadMoreCourses.js
  tcf_website/templates/common/rating_card.html
  tcf_website/templates/course/course.html
  tcf_website/templates/course/course_professor.html
  tcf_website/views/browse.py
Labels: Needs Review

#244 Add copyright year correctly & dynamically
  tcf_website/templates/base/base.html
  tcf_website/templates/base/sidebar.html
  tcf_website/templates/landing/landing.html
Labels: bug

#240 Refactor and improve the speed of /course/{course_id}
  tcf_website/templates/course/course.html
  tcf_website/views/browse.py
Labels: Enhancement

#246 URL after login
  tcf_core/settings.py
  tcf_website/urls.py
Labels: bug

#253 Fix #252 Duplicate data in the Instructor API
  tcf_website/api/filters.py
  tcf_website/api/views.py
Labels: Jennifer, bug

#256 Add course, instructor params to Semester API
  tcf_website/api/views.py
Labels: Enhancement

#257 Add recency param to Instructor API
  precommit
  tcf_website/api/filters.py
  tcf_website/api/paginations.py
  tcf_website/api/views.py
  tcf_website/templates/department/department.html
  tcf_website/tests/test_course.py
Labels: Enhancement

#242 Improve the performance of reviews without client-side rendering
  tcf_website/models/models.py
  tcf_website/templates/reviews/review.html
Labels: Enhancement

#215 Write review form
  tcf_website/api/filters.py
  tcf_website/api/views.py
  tcf_website/static/base/base.css
  tcf_website/static/base/tcf-style.css
  tcf_website/static/icons/icons.html
  tcf_website/static/reviews/new_review.css
  tcf_website/static/reviews/new_review.js
  tcf_website/templates/base/coming_soon_modal.html
  tcf_website/templates/base/index.html
  tcf_website/templates/base/sidebar.html
  tcf_website/templates/course/course.html
  tcf_website/templates/reviews/new.html
  tcf_website/templates/reviews/new_review.html
  tcf_website/templates/reviews/review.html
  tcf_website/templates/reviews/reviews.html
  tcf_website/templates/reviews/user_reviews.html
  tcf_website/urls.py
  tcf_website/views/review.py
Labels: 🔎 Needs Review

#288 Refactor build files
  .travis.yml
  Dockerfile
  app.yaml
Labels: ⚙ CI/CD

#286 Force-redirect to HTTPS on Heroku
  tcf_core/settings.py
Labels: ⚙ CI/CD
