Repository thecourseforum/theCourseForum2, pull requests merged in 2020-12, with the labels that each got.

#292 Lous suggestion
  .gitignore
  FOR-DEVS.md
  _SCRIPTS/LousListScript.md
  _SCRIPTS/legacy_db/mysql2sqlite
  _SCRIPTS/legacy_db/mysql2sqlite2
  _SCRIPTS/load_data
  bootstrap_vagrant.sh
  db/DBSchema.png
  db/LousListScript.md
  db/export_mapping_table.sql
  db/lous20201107.csv
  docker-compose.yml
Labels: 🔎 Needs Review

#284 Upgrade Python version
  .travis.yml
  Dockerfile
  app.yaml.template
  runtime.txt
Labels: ⚙ CI/CD

#237 Lous list script
  .gitignore
  FOR-DEVS.md
  db/DBSchema.png
  db/LousListScript.md
  db/export_mapping_table.sql
  docker-compose.yml
  legacy_db/mysql2sqlite
  legacy_db/mysql2sqlite2
  load_data
Labels: 🔎 Needs Review

#291 Statistics on My Review page
  tcf_website/static/reviews/review_stats.css
  tcf_website/templates/reviews/review_stats.html
  tcf_website/templates/reviews/user_reviews.html
  tcf_website/views/profile.py
Labels: ⚖ Parity, 🔎 Needs Review

#325 Review form fixes
  tcf_website/api/views.py
  tcf_website/static/reviews/new_review.js
  tcf_website/templates/reviews/review_stats.html
  tcf_website/templates/reviews/user_reviews.html
Labels: 🔎 Needs Review

#322 Course-Instructor dropdown + UI
  tcf_website/static/base/base.css
  tcf_website/static/course/course_professor.css
  tcf_website/static/course/javascript/instr_data.js
  tcf_website/templates/common/toolbar.html
  tcf_website/templates/course/course_professor.html
  tcf_website/views/browse.py
Labels: 🔎 Needs Review

#312 Login modal
  tcf_website/templates/about/logo-tagline.html
  tcf_website/templates/base/index.html
  tcf_website/templates/base/navbar.html
  tcf_website/templates/base/sidebar.html
  tcf_website/templates/landing/landing.html
  tcf_website/templates/login/login.html
  tcf_website/templates/login/login_base.html
  tcf_website/templates/login/login_button.html
  tcf_website/templates/login/login_modal.html
  tcf_website/views/auth.py
Labels: 🔎 Needs Review

#336 Patch v1.1.3
  tcf_website/templates/login/extra_info_form.html
Labels: Release
