Repository thecourseforum/theCourseForum2, pull requests merged in 2021-02, with the labels that each got.

#359 Add 'deleted review' message on reviews page
  tcf_website/tests/test_review.py
  tcf_website/views/review.py
Labels: 🔎 Needs Review

#362 Fix #361 404 Not found when clicking privacy policy
  tcf_website/templates/landing/_faqs.json
  tcf_website/templates/landing/landing.html
  tcf_website/views/index.py
Labels: 🐛 bug

#344 GitHub actions
  .config/.env.example
  .config/.env.travis
  .config/app.yaml.template
  .dockerignore
  .github/workflows/continuous-integration.yml
  .github/workflows/master-to-app-engine.yml
  .gitignore
  .travis.yml
  README.md
  Vagrantfile
  bootstrap_vagrant.sh
  docker-compose.yml
  docs/FOR-DEVS.md
  package.json
  scripts/notify-discord.sh
  tcf_core/settings/__init__.py
  tcf_core/settings/base.py
  tcf_core/settings/ci.py
  tcf_core/settings/dev.py
  tcf_core/settings/prod.py
Labels: ⚙ CI/CD

#380 Removed docs moved to wiki
  .github/workflows/continuous-integration.yml
  db/LousListScript.md
  docs/FOR-DEVS.md
Labels: Documentation

#384 Fix deployment condition
  .github/workflows/master-to-app-engine.yml
Labels: Bug

#385 Add missing environment variable in deployment script
  .github/workflows/master-to-app-engine.yml
Labels: Bug

#386 Remove duplicate keys in app.yaml.template
  .config/app.yaml.template
Labels: Bug

#388 Add missing environment variable in app.yaml.template
  .config/app.yaml.template
Labels: Bug

#394 Faster precommit
  .github/workflows/continuous-integration.yml
  .gitignore
  precommit
Labels: CI/CD

#350 Fix mobile review card
  tcf_website/static/base/base.css
  tcf_website/static/reviews/review.css
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/reviews/review.html
  tcf_website/templates/reviews/reviews.html
  tcf_website/templates/reviews/user_reviews.html
Labels: Needs Review

#341 Refactor and fix course_instructor page
  tcf_website/management/commands/load_grades.py
  tcf_website/models/models.py
  tcf_website/static/course/javascript/course_data.js
  tcf_website/templates/instructor/instructor.html
  tcf_website/views/browse.py
Labels: Bug, Refactoring

#407 Add discord notification for deployment
  .github/workflows/master-to-app-engine.yml
  scripts/notify-deployment-result.sh
Labels: CI/CD

#418 Disable django-silk on Heroku/GAE
  tcf_core/settings/__init__.py
Labels: Bug
