Repository thecourseforum/theCourseForum2, pull requests merged in 2021-03, with the labels that each got.

#421 Fix uncaught TypeError in Developer Console
  tcf_website/templates/landing/landing.html
Labels: Bug

#391 Completed Ascending/Descending Sort Buttons
  tcf_website/static/department/sortClasses.js
  tcf_website/templates/common/toolbar.html
Labels: In Progress

#351 Review collapser
  tcf_website/static/reviews/review.css
  tcf_website/static/reviews/review.js
  tcf_website/templates/reviews/review.html
Labels: Feature

#423 Improve instructor_view
  tcf_website/models/models.py
  tcf_website/templates/instructor/instructor.html
  tcf_website/tests/test_instructor.py
  tcf_website/views/browse.py
Labels: Bug, Performance

#399 Prevent user from spamming submit for reviews/multiple reviews for sa…
  tcf_website/templates/reviews/duplicate_review_modal.html
  tcf_website/templates/reviews/new_review.html
  tcf_website/urls.py
  tcf_website/views/review.py
Labels: Needs Review

#430 Prevent precommit gotchas
  .gitattributes
  precommit.sh
Labels: CI/CD, Refactoring

#437 Made Alexa's photo render on alum's page
  precommit.sh
  tcf_website/static/about/alum-pfps/agomez.jpeg
  tcf_website/static/about/team-pfps/ENG_Alexa_Gomez.jpg
  tcf_website/static/about/team-pfps/ENG_Amrit_Gorle.jpg
  tcf_website/static/about/team-pfps/ENG_Brad_Knaysi.jpg
  tcf_website/static/about/team-pfps/ENG_Brian_Yu.jpg
  tcf_website/static/about/team-pfps/ENG_Erick_Tian.jpg
  tcf_website/static/about/team-pfps/ENG_Jasmine_Dogu.jpg
  tcf_website/static/about/team-pfps/ENG_Mara_Hart.jpg
  tcf_website/static/about/team-pfps/ENG_Neal_Patel.jpg
  tcf_website/static/about/team-pfps/ENG_Nikash_Sethi.jpg
  tcf_website/static/about/team-pfps/ENG_Sai_Konuri.jpg
  tcf_website/views/team_alums.json
Labels: Bug, Needs Review

#436 Take out `continue-on-error` from GitHub Actions
  .github/workflows/continuous-integration.yml
Labels: Bug

#444 Add banner ad to browse
  tcf_website/templates/browse/browse.html
  tcf_website/templates/common/banner_ad.html
  tcf_website/urls.py
  tcf_website/views/__init__.py
  tcf_website/views/ads.py
Labels: Needs Review

#442 Remove chart.js from package.json
  package-lock.json
  package.json
Labels: Refactoring

#441 Fix the `edit-review` bug (sum of hours)
  tcf_website/tests/test_review.py
  tcf_website/views/review.py
Labels: Bug

#425 Wrote enough tests to cover the models file (now at 84% coverage over…
  tcf_website/tests/test_browse.py
  tcf_website/tests/test_course.py
  tcf_website/tests/test_instructor.py
  tcf_website/tests/test_instructor_edgecases.py
  tcf_website/tests/test_misc_models.py
  tcf_website/tests/test_review.py
  tcf_website/tests/test_semester.py
  tcf_website/tests/test_subdepartment.py
  tcf_website/tests/test_user.py
  tcf_website/tests/test_utils.py
Labels: Testing

#452 Display total number of reviews for a given course (with or without t…
  tcf_website/templates/course/course_professor.html
  tcf_website/views/browse.py
Labels: Needs Review

#450 Improve discord notification
  .github/workflows/continuous-integration.yml
  scripts/notify-checks-result.sh
  scripts/notify-deployment-result.sh
Labels: CI/CD

#417 Changed review model and view to display both upvotes and downvotes
  tcf_website/models/models.py
  tcf_website/static/reviews/review.css
  tcf_website/static/reviews/review.js
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/reviews/review.html
  tcf_website/templates/reviews/review_form_content.html
  tcf_website/tests/test_review.py
Labels: Needs Review
