Repository thecourseforum/theCourseForum2, pull requests merged in 2021-04, with the labels that each got.

#473 Housekeeping
  Dockerfile
  requirements.txt
  tcf_core/settings/base.py
Labels: CI/CD

#480 Adsense
  tcf_website/templates/browse/browse.html
  tcf_website/templates/common/leaderboard_ad.html
  tcf_website/templates/common/toolbar.html
  tcf_website/templates/course/course.html
  tcf_website/templates/course/course_professor.html
  tcf_website/templates/department/department.html
  tcf_website/templates/search/search.html
Labels: Needs Review

#443 Emoji reorder
  tcf_website/static/reviews/review.css
  tcf_website/templates/reviews/review.html
Labels: Needs Review

#484 Temporary fix for broken Pylint 2.8.0
  requirements.txt
Labels: Bug
